# Generated by Django 2.0.5 on 2018-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_ru',
            field=models.TextField(null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_uk',
            field=models.TextField(null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
