# Generated by Django 2.0.5 on 2018-06-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Дата и время начала занятия')),
                ('date_end', models.DateTimeField(verbose_name='Дата и время завершения занятия')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.ClubLesson')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
