# Generated by Django 2.0.5 on 2018-06-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='image',
            name='alt_en',
        ),
        migrations.RemoveField(
            model_name='image',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='image',
            name='alt_uk',
        ),
    ]
