# Generated by Django 2.0.5 on 2018-06-11 14:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180611_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
