# Generated by Django 2.0.5 on 2018-06-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180611_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='quantity',
            field=models.PositiveIntegerField(default=4, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
