# Generated by Django 2.0.5 on 2018-06-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Оформленна'),
        ),
    ]
