# Generated by Django 2.0.5 on 2018-06-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
