# Generated by Django 2.0.5 on 2018-06-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=230, null=True, unique=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова')),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='ClubAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Администратор клуба',
                'verbose_name_plural': 'Администраторы клубов',
            },
        ),
        migrations.CreateModel(
            name='ClubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/clubs/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение клуба',
                'verbose_name_plural': 'Изображения клубов',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='ClubLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
