# Generated by Django 2.0.5 on 2018-06-11 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='children',
            field=models.ManyToManyField(to='user_profile.Child'),
        ),
        migrations.AddField(
            model_name='group',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='club',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='club',
            name='super_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Administrator', verbose_name='Главный администратор клуба'),
        ),
    ]
