# Generated by Django 2.0.5 on 2018-06-08 11:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=colorfield.fields.ColorField(default='#238a53', max_length=18, verbose_name='Цвет'),
        ),
    ]
