# Generated by Django 2.0.5 on 2018-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20180611_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='children',
            field=models.ManyToManyField(blank=True, to='user_profile.Child'),
        ),
    ]
