# Generated by Django 2.0.5 on 2018-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='course',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=16, verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
